football_website/urls.py
from football_website.settings import MEDIA_ROOT
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls.conf import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name='home'
urlpatterns = [
    path('', views.home, name='home'),
    path('club_squad/', views.club_directory, name='club_squad'),
    path('result/', views.result, name='result'),
    path('point_table/', views.point_table, name='point_table'),
    path('news/', views.news, name='news'),
    path('news/<int:news_id>/', views.news_detail, name='news_detail'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('fan_club/login/', LoginView.as_view(), name='login'),
    path('fan_club/logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register')
]

home/models.py
from django.db import models


class LeagueTeam(models.Model):
    name = models.CharField(max_length=50)
    points = models.IntegerField(default=0)
    matches_played = models.IntegerField(default=0)
    win = models.IntegerField(default=0)
    lost = models.IntegerField(default=0)
    draw = models.IntegerField(default=0)
    goal_scored = models.IntegerField(default=0)
    goal_recieved = models.IntegerField(default=0)
    logo_url =models.URLField(max_length=200)


    class Meta:
        ordering = ('-points',)

    def __str__(self):
        return self.name



class Player(models.Model):
    full_name = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    image_url = models.URLField(max_length=200)

    def __str__(self):
        return self.full_name


class Squad(models.Model):
    image_url = models.URLField(max_length=200)
    role = models.CharField(max_length=50)
    full_name = models.CharField(max_length=50)
    rank = models.IntegerField()


    class Meta:
        ordering = ('rank',)

    def __str__(self):
        return self.role

class News(models.Model):
    image_url = models.URLField(max_length=200)
    title = models.CharField(max_length=250)
    date_added = models.DateTimeField(auto_now_add=True)
    text = models.TextField()


    class Meta:
        ordering = ('-date_added',)
        verbose_name = 'News'
        verbose_name_plural = 'News'


    def __str__(self):
        return self.title
    

# Create your models here.
class Match(models.Model):
    match_number = models.IntegerField()
    host_team = models.CharField(max_length=250)
    host_team_logo_url = models.URLField(max_length=200, null=True, blank=True)
    host_team_score = models.IntegerField(default=0)
    guest_team_score = models.IntegerField(default=0)
    guest_team = models.CharField(max_length=250)
    guest_team_logo_url = models.URLField(max_length=200, null=True, blank=True)
    stadium = models.CharField(max_length=250, default='Oq-Tepa Stadium')
    date = models.DateTimeField(auto_now_add=False)
    previous_match = models.BooleanField(default=True)

    class Meta:
        ordering = ('-match_number',)


    def __str__(self):
        return f'Match {self.match_number} between {self.host_team} and {self.guest_team}'

home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import fields

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')


    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password2'] != cd['password']:
            raise forms.ValidationError('Passwords don\'t match.')
        
        return cd['password2']

home/views.py
from django.core import paginator
from django.shortcuts import render
from .forms import UserRegistrationForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import LeagueTeam, Match, News, Player, Squad
# Create your views here.

def home(request):

    matches = Match.objects.all()[:4]
    news = News.objects.all()[:4]
    main_news = news[0]
    other_news = news[1:4]


    return render(request, 'home/index.html', {'matches': matches, 'main_news': main_news, 'other_news': other_news,})


def club_directory(request):
    squad = Squad.objects.all()
    players = Player.objects.all()

    return render(request, 'home/club_squad.html', {'squad': squad, 'players': players})



def result( request):
    results = Match.objects.all()
    print(results)

    return render(request, 'home/results.html', {'results': results})


def point_table(request):
    league_teams = LeagueTeam.objects.all()
    d = {}
    for i in range(1,len(league_teams)+1):
        d[i] = league_teams[i-1]

    return render(request, 'home/point_table.html', {'league_teams': d})



def news(request):
    news_list = News.objects.all()
    paginator = Paginator(news_list, 4)
    page = request.GET.get('page')

    try:
        news_list = paginator.page(page)
    except PageNotAnInteger:
        news_list = paginator.page(1)
    except EmptyPage:
        news_list = paginator.page(paginator.num_pages)



    return render(request, 'home/news.html', {'news_list':news_list, 'page': page})


def news_detail(request, news_id):
    news = News.objects.get(id=news_id)

    return render(request, 'home/news_detail.html', {'news':news})


def dashboard(request):

    return render(request, 'home/dashboard.html')


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'home/register_done.html', {'new_user': new_user})

    else:
        user_form = UserRegistrationForm()

        return render(request, 'home/register.html', {'user_form': user_form})

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/icon" href="{% static 'img/fav.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/f68d03869f.js" crossorigin="anonymous"></script>
    <title>OQ-TEPA FC</title>
    <link href="https://fonts.googleapis.com/css2?family=Sawarabi+Mincho&family=Source+Serif+Pro&display=swap"
        rel="stylesheet">
</head>

<body>
    <div class="base">
        <div class="social-links hide-me part-a">
            <div><i class="fab fa-facebook-square fa-2x"></i></div>
            <div><i class="fab fa-instagram-square fa-2x"></i></div>
            <div><i class="fab fa-twitter-square fa-2x"></i></div>
            <div><i class="fab fa-youtube-square fa-2x"></i></div>
            <div><i class="fab fa-telegram fa-2x"></i></div>
        </div>
        <nav>
            <div class="logo">
                    <div class="logo-image"><img src="https://storage.googleapis.com/cpt-partners-content-prod/0709f6c7-a945-44e3-8f6c-3bbd82c2eb5c.png" alt=""></div>
                    <div class="logo-name">OQ-TEPA FC</div>
            </div>
            <ul class="nav-list">
                <li class="nav-link"><a href="{% url 'home:home' %}">Home</a></li>
                <li class="nav-link"><a href="{% url 'home:club_squad' %}">Club Squad</a></li>
                <li class="nav-link"><a href="{% url 'home:result' %}">Results</a></li>
                <li class="nav-link"><a href="{% url 'home:point_table' %}">Point Table</a></li>
                <li class="nav-link"><a href="{% url 'home:news' %}">News</a></li>
                {% if request.user.is_authenticated %}
                <li class="nav-link">
                    <a href="{% url 'home:dashboard' %}">Hello, {{user.username}}</a>
                </li>
                {% else %}
                <li class="nav-link"><a href="{% url 'home:login' %}">Fan Club Log-in</a></li>
                {% endif %}
            </ul>
            <ul id="mySidebar">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                <li class="nav-link"><a href="{% url 'home:home' %}">Home</a></li>
                <li class="nav-link"><a href="{% url 'home:club_squad' %}">Club Squad</a></li>
                <li class="nav-link"><a href="{% url 'home:result' %}">Results</a></li>
                <li class="nav-link"><a href="{% url 'home:point_table' %}">Point Table</a></li>
                <li class="nav-link"><a href="{% url 'home:news' %}">News</a></li>
                {% if request.user.is_authenticated %}
                <li class="nav-link">
                    <a href="{% url 'home:dashboard' %}">Hello, {{user.username}}</a>
                </li>
                {% else %}
                <li class="nav-link"><a href="{% url 'home:login' %}">Fan Club Log-in</a></li>
                {% endif %}
                <div class="social-links inside part-a">
                    <div><i class="fab fa-facebook-square fa-2x"></i></div>
                    <div><i class="fab fa-instagram-square fa-2x"></i></div>
                    <div><i class="fab fa-twitter-square fa-2x"></i></div>
                    <div><i class="fab fa-youtube-square fa-2x"></i></div>
                    <div><i class="fab fa-telegram fa-2x"></i></div>
                </div>
            </ul>
            <div class="openbtn">
                <button class="openbtn" onclick="openNav()">&#9776;</button>
            </div>
        </nav>
        
        {% block content %}
      
        {% endblock content %}
        <footer>
            <h2>OQ-TEPA FC</h2>
            <div class="social-links">
                <div><i class="fab fa-facebook-square fa-2x"></i></div>
                <div><i class="fab fa-instagram-square fa-2x"></i></div>
                <div><i class="fab fa-twitter-square fa-2x"></i></div>
                <div><i class="fab fa-youtube-square fa-2x"></i></div>
                <div><i class="fab fa-telegram fa-2x"></i></div>
            </div>
            <p>© Copyright 2021 The Oq-tepa Football Club and Athletic Grounds Limited.</p>
            <p>Nurmatov Abdurakhimbek</p>
        </footer>
    </div>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

home/templates/home/club_squad.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>Coaches</h1>
  <section class="staff">
      {% for person in squad %}
      <div class="main-staff">
          <img src="{{person.image_url}}" alt="">
          <h5>{{person.role}}</h5>
          <h5>{{person.full_name}}</h5>
      </div>
      {% endfor %}
  </section>
  <h1>Players</h1>
  <section class="players">
    {% for player in players %}
    <div class="main-players">
        <img src="{{player.image_url}}" alt="">
        <h5>{{player.position}}</h5>
        <h5>{{player.full_name}}</h5>
    </div>
    {% endfor %}
  </section>
{% endblock content %}

home/templates/home/dashboard.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="logged-in">
    <h1>Welcome, {{user.username}}</h1>
    <a href="{% url 'home:logout' %}"><button class="btn">Log-out</button></a>
</div>
<img width="800px" src="https://i2-prod.chroniclelive.co.uk/incoming/article15598911.ece/ALTERNATES/s1200/0_Sunderland-v-Bradford-City-Sky-Bet-League-One.jpg" alt="">
{% endblock content %}

home/templates/home/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="slideshow-container">
    <div class="mySlides first fade">
        <div class="numbertext">1/3</div>
        <img src="{% static 'img/ball.jpg' %}" alt="">
        <div class="text">Caption text</div>

    </div>
    <div class="mySlides fade">
        <div class="numbertext">1/3</div>
        <img src="{% static 'img/player.jpg' %}" alt="" style="width: 100%;">
        <div class="text">Caption text</div>

    </div>
    <div class="mySlides fade">
        <div class="numbertext">1/3</div>
        <img src="{% static 'img/hames.jpg' %}" alt="" style="width: 100%;">
        <div class="text">Caption text</div>
    </div>

    <a onclick="plusSlides(-1)" class="prev">&#10094;</a>
    <a onclick="plusSlides(-1)" class="next">&#10095;</a>
</div>

<div style="text-align: center;">
    <span class="dot" onclick="currentSlide(1)" ></span>
    <span class="dot" onclick="currentSlide(2)" ></span>
    <span class="dot" onclick="currentSlide(3)" ></span>
</div>
<main class="container">
    <div class="match">
        {% for match in matches %}
        {% if not match.previous_match %}
        <div class="upcoming-match">
            <h3>Upcoming-match</h3>
            <div class="upcoming-board">
                <div class="home">
                    <img width="50px" src="{{match.host_team_logo_url}}" alt="">
                    <p>OQ-TEPA FC</p>
                </div>
                <div>VS</div>
                <div class="away">
                    <img width="40px" src="{{match.guest_team_logo_url}}" alt="">
                    <p>PAKHTAKOR FC</p>
                </div>
            </div>
            <p>{{match.stadium}} | {{match.date|date:'M d, Y'}}</p>
            <p>{{match.date|date:'H:i'}}</p>
        </div>
        {% endif %}
        {% endfor %}
        <div class="last-match">
            <iframe width="100%" height="100%" src="https://www.youtube.com/embed/l-erXHwJNIU" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="previous-matches">
            {% for match in matches %}
            {% if match.previous_match %}
            <div class="upcoming-match">
                <h3>Match {{match.match_number}}</h3>
                <div class="upcoming-board">
                    <div class="home">
                        <img width="50px" src="{{match.host_team_logo_url}}" alt="">
                        <p>{{match.host_team}}</p>
                    </div>
                    <div>{{match.host_team_score}} : {{match.guest_team_score}}</div>
                    <div class="away">
                        <img width="40px" src="{{match.guest_team_logo_url}}" alt="">
                        <p>{{match.guest_team}}</p>
                    </div>
                </div>
                <p>{{match.stadium}} | {{match.date|date:'M d, Y'}}</p>
                <p>{{match.date|date:'H:i'}}</p>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="news-table-fixture">
        <div class="news">
            <h1 class="news_heading">News</h1>
            <div class="news-main-box">
                <img src="{{main_news.image_url}}" alt="">
                <h2 class="news-title"><a href="{% url 'home:news_detail' main_news.id %}">{{main_news.title}}</a></h2>
            </div>
            {% for news in other_news %}
            <div class="news-small-box">
                <img src="{{news.image_url}}" alt="">
                <p class="news-title"><a href="{% url 'home:news_detail' news.id %}">{{news.title}}</a></p>
            </div>
            {% endfor %}
            
        </div>
        <div class="table-fixture">
            <div class="point-table">
                <h1 class="table">Point table</h1>
                <img src="{% static 'img/table.jpg' %}" alt="">
            </div>
            <div class="fixture">
                <h1 class="match-fixture">Match fixture</h1>
                {% for match in matches %}
        {% if not match.previous_match %}
        <div class="upcoming-match">
            <h3>Upcoming-match</h3>
            <div class="upcoming-board">
                <div class="home">
                    <img width="50px" src="{{match.host_team_logo_url}}" alt="">
                    <p>OQ-TEPA FC</p>
                </div>
                <div>VS</div>
                <div class="away">
                    <img width="40px" src="{{match.guest_team_logo_url}}" alt="">
                    <p>PAKHTAKOR FC</p>
                </div>
            </div>
            <p>{{match.stadium}} | {{match.date|date:'M d, Y'}}</p>
            <p>{{match.date|date:'H:i'}}</p>
        </div>
        {% endif %}
        {% endfor %}
            </div>
        </div>
    </div>
    <div class="about">
        <div class="about-container">
            <div class="about-text">
                <h2>WHO WE ARE.</h2>
                <p>
                    Oq Tepa FC is a professional football club in Tashkent, Uzbekistan, that competes in the Super Liga, the top tier of Uzbek football. 
                </p>
                <button class="btn">Read more</button>
            </div>
            <div class="about-img">
                <img width="400px" src="https://rstheme.com/products/html/khelo/images/about/about-home.png" alt="">
            </div>
        </div>
    </div>
</main>
<div class="gallery-container">
    <div class="gallery">
        <h2 class="red-heading">GALLERY</h2>
        <div class="g-content">
            <div class="box1"><img src="https://daily.jstor.org/wp-content/uploads/2018/06/soccer_europe_1050x700.jpg" alt=""></div>
            <div class="box2"><img src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iDt6V.rPqgC0/v1/1000x-1.jpg" alt=""></div>
            <div class="box3"><img src="https://www.worldsoccer.com/wp-content/uploads/2020/11/GettyImages-1190255069-600x490.jpg" alt=""></div>
            <div class="box4"><img src="https://soccer.nbcsports.com/wp-content/uploads/sites/14/2020/02/GettyImages-1198667035-e1580869734123.jpg" alt=""></div>
            <div class="box5"><img src="https://thumbor.forbes.com/thumbor/fit-in/1200x0/filters%3Aformat%28jpg%29/https%3A%2F%2Fspecials-images.forbesimg.com%2Fimageserve%2F5f3a839ed446d5a0755ba4b3%2F0x0.jpg" alt=""></div>
        </div>
    </div>
</div>
{% endblock content %}

home/templates/home/news.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>Latest News</h1>
    <ul class="news-list">
        {% for news in news_list %}
        <li>
            <div class="img-news-list">
                <img src="{{news.image_url}}" alt="">
            </div>
            <div class="text-news">
                <h3><a href="{% url 'home:news_detail' news.id %}">{{news.title}}</a></h3>
                <p>{{news.date_added|date:'d-m-Y'}}</p>
                <p>{{news.text|truncatewords:25}}</p>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% include "pagination.html" with page=news_list %}
{% endblock content %}

home/templates/home/news_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="news-detail">
        <h1>{{news.title}}</h1>
        <img src="{{news.image_url}}" alt="">
        <p>{{news.date_added|date:'d-m-Y'}}</p>
        <p>{{news.text|linebreaks}}</p>
    </div>
{% endblock content %}

home/templates/home/point_table.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>League Table</h1>
  <ul class="league-table">
      <li>
          <h3> </h3>
          <h3> </h3>
          <h3>Team</h3>
          <h3>M</h3>
          <h3>W</h3>
          <h3>D</h3>
          <h3>L</h3>
          <h3>Points</h3>
      </li>
      {% for key, team in league_teams.items %}
      <li>
        <h3>{{key}}</h3>
        <h3><img width="50px" src="{{team.logo_url}}" alt=""></h3>
        <h3>{{team.name}}</h3>
        <h3>{{team.matches_played}}</h3>
        <h3>{{team.win}}</h3>
        <h3>{{team.draw}}</h3>
        <h3>{{team.lost}}</h3>
        <h3>{{team.points}}</h3>
      </li>
      {% endfor %}
  </ul>
{% endblock content %}

home/templates/home/register.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h1>Create an account</h1>
<p>Please, sign up using the following form:</p>
<form method="post" class="main-form">
    {{ user_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" class="btn" value="Create my account"></p>
</form>
{% endblock content %}

home/templates/home/register_done.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>Welcome {{ new_user.first_name }}!</h1>
    <h3>Your account has been successfully created. Now you can <a href="{% url 'home:login' %}">log in</a>.</h3>
{% endblock %}

home/templates/home/results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Results</h1>
  <ul class="match-list">
      {% for match in results %}
        <li>
            <h3 id="match-num">Match {{match.match_number}}</h3>
            <div><img width="50px" src="{{match.host_team_logo_url}}" alt=""> </div>
            <h3>{{match.host_team}}</h3> 
            <div>
                <h3>{{match.host_team_score}} : {{match.guest_team_score}}</h3>
            </div>
            <h3>{{match.guest_team}}</h3>
            <div><img width="50px" src="{{match.guest_team_logo_url}}" alt=""></div> 
        </li>
      {% endfor %}
  </ul>
{% endblock content %}

home/templates/pagination.html
<div class="paginator">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}"><button class="btn">Previous</button></a>
        {% endif %}
        <b>{{page.number}} out of {{page.paginator.num_pages}}</b>
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}"><button class="btn">Next</button></a>
        {% endif %}
</div>